### ISSUE TITLE
Create a Sidebar

### ISSUE THREAD

**Issue by poojanV55** [clubgamma/Twitter-Web-Clone#1]
Create a navbar similar to as shown in the red box image below. Can make the components as shown in the image and also add any of your own to give it a new twist.

![tweet3](https://user-images.githubusercontent.com/63559515/135341049-ac58563c-fae0-4ce9-919c-7252a45619ff.png)

You can also check twitter website for better understanding ,
Happy hacking 🤩!

**Comment by georgioupanayiotis** [comment]
@poojanV55 can you assign me this issue ?

**Comment by saheelsapovadia** [comment]
@poojanV55 this looks interesting, can you assign this issue?

**Comment by poojanV55** [comment]
Yes sure @georgioupanayiotis 

Happy Hacking!

**Comment by saheelsapovadia** [comment]
@poojanV55 can you please assign this to me, I already submitted a pr #5

**Comment by poojanV55** [comment]
@georgioupanayiotis  Can you please provide till when the work would be completed ?
