### ISSUE TITLE
Messages pop up

### ISSUE THREAD

**Issue by saheelsapovadia** [clubgamma/Twitter-Web-Clone#15]
Create a messages pop up in bottom right corner, reference image attached.

collapsed-
![image](https://user-images.githubusercontent.com/59962703/135737903-dcb77125-17db-4940-93ba-bfd942510dcb.png)

expanded-
![image](https://user-images.githubusercontent.com/59962703/135737917-71c1d500-3a62-49dd-8aaf-ecb6aa107101.png)

**Comment by saheelsapovadia** [comment]
@poojanV55 please add the `hacktoberfest` label and assign this to me 😃.

**Comment by poojanV55** [comment]
I have assigned it to you , You can work on it :)
Happy Hacking :)
