### ISSUE TITLE
Fix the issue of overlapping 

### ISSUE THREAD

**Issue by poojanV55** [clubgamma/Twitter-Web-Clone#26]
When opening the messaging section at right side of the page , when expanded the line in the background is overlapped which needed to be fixed.

**Comment by poojanV55** [comment]
> Can you please check once if the PR that I've created sorts your issue or not?

Yes ! , The issue has been solved @sakshi-e-glitch  , Thank you for  the contribution :)

Happy Hacking 😄

**Comment by sakshi-e-glitch** [comment]
@poojanV55 can you add hacktoberfest-accepted label as well or will it be added after the 14days maturity period?
