### ISSUE TITLE
Designing the messages sections

### ISSUE THREAD

**Issue by poojanV55** [clubgamma/Twitter-Web-Clone#27]
Design the messages section which can be seen when clicked . For reference you can check twitter websites messages section .

Happy Hacking 😄

**Comment by MaitriDA** [comment]
Please can you assign me this issue. I have worked on a chat application (web) before.

**Comment by poojanV55** [comment]
You are the assignee now , you can work on it @MaitriDA  :)

Happy Hacking 😄

**Comment by MaitriDA** [comment]
Should I add message section code in index.html or make a new file as message.html
