### ISSUE TITLE
Add Trending section

### ISSUE THREAD

**Issue by poojanV55** [clubgamma/Twitter-Web-Clone#3]
Add the trending section which is shown in the red box shown in the below image.

![tweet3](https://user-images.githubusercontent.com/63559515/135340814-7fbf0f8f-5160-4e26-ad7c-d8ce8cc15476.png)

Happy Hacking 🤩!

**Comment by muskanshaikh** [comment]
can i work on this

**Comment by poojanV55** [comment]
Yes sure @muskanshaikh
I have made you the assignee.
Happy Hacking :)

**Comment by MaitriDA** [comment]
Can you assign me this issue.

**Comment by poojanV55** [comment]
yes sure @MaitriDA  ,I have assigned it to you :)

Happy hacking 😄
