### ISSUE TITLE
Add Signup page

### ISSUE THREAD

**Issue by poojanV55** [clubgamma/Twitter-Web-Clone#6]
Add signup page similar shown in the image .
You can either make it light mode too...
![image](https://user-images.githubusercontent.com/63559515/135577388-c1087b14-e6ed-4dee-a65b-65aa71eaf2d2.png)

**Comment by gokhalevedant06** [comment]
Hi, I would like to work on this

**Comment by poojanV55** [comment]
Yes sure @gokhalevedant06 , I have made you the assignee.

Happy Hacking:)
