### ISSUE TITLE
Add Login page 

### ISSUE THREAD

**Issue by poojanV55** [clubgamma/Twitter-Web-Clone#7]
You can check the twitter login module and can create something similar. 

Happy Hacking :)

**Comment by suprabhat25** [comment]
Can you assign this issue to me?

**Comment by poojanV55** [comment]
Yes  Sure @suprabhat25 , I have made you the assignee.

Happy Hacking:)

**Comment by hrushikeshrout** [comment]
Hi, I want to add a login page to this site. Can you please assign me this issue?

**Comment by suprabhat25** [comment]
@hrushikeshrout you can't be assigned this issue as I am working on it. Please consider another issue.

**Comment by poojanV55** [comment]
Sorry @hrushikeshrout, the issue has already been assigned ,

You can look for other issues or can also create a new one  ; )

Happy Hacking : )

**Comment by gokhalevedant06** [comment]
Hi, @poojanV55 If no one is working on this should I try this out? I had completed signup page #10 successfully. I will be able to do this too.

**Comment by poojanV55** [comment]
Hello @suprabhat25 can you please acknowledge till when will you be completing the task ...

If not working on it then I can assign it to others

**Comment by suprabhat25** [comment]
Please to someone else.
